### PR TITLE
Issue 72 user profile

### PR DESCRIPTION
**Pull request by wbvtler**
Implements issue #72 

EDUrain App

### CODE REVIEW

**Comment by tomdng** [comment]
Hey @wbvtler I think the UI is looking good but in the `profileActions.js` file, but the development endpoint uses the fafsa endpoint rather than the demographics endpoint (line 7). The production endpoint is right, so if you can update the development endpoint and adjust the `ProfilePage.js` component to work with that data instead, we can push to production without any unexpected behavior.

**Comment by wbvtler** [comment]
@tomdng I see I did forget to fix that. However, the `/demographics` endpoint does not retrieve the correct data. All of the responses to the `/demographics` (which is not even all of them) return `null`. 

<details>
<summary>`/demographics` Response Payload:</summary>

```JavaScript
{
  "questions":[
    {
      "id":"gQ5KNg8A",
      "type":"select",
      "name":"gender",
      "data":"Gender",
      "hint":null,
      "choices":[...],
      "response":{
        "answer_name":null,
        "answer":null
      }
    },
    {
      "id":"407G2g5G",
      "type":"select",
      "name":"race",
      "data":"Race",
      "hint":null,
      "choices":[...],
      "response":{
        "answer_name":null,
        "answer":null
      }
    },
    {
      "id":"gq516x74",
      "type":"multi",
      "name":"ethnicity",
      "data":"Ethnicity",
      "hint":null,
      "choices":[...],
      "response":{
        "answer_name":null,
        "answer":null
      }
    },
    {
      "id":"9n8gML73",
      "type":"select",
      "name":"religion",
      "data":"Religion",
      "hint":null,
      "choices":[...],
      "response":{
        "answer_name":null,
        "answer":null
      }
    },
    {
      "id":"2VzYyPzZ",
      "type":"select",
      "name":"country",
      "data":"County of Heritage",
      "hint":null,
      "choices":[...],
      "response":{
        "answer_name":null,
        "answer":null
      }
    },
    {
      "id":"nNzDpjz2",
      "type":"multi",
      "name":"major",
      "data":"Major \/ Area of Study",
      "hint":null,
      "choices":[...],
      "response":{
        "answer_name":null,
        "answer":null
      }
    }
  ]
}

```

</details>

**Review by tomdng — APPROVED** [review]
@wbvtler ah so that's why I kept getting an empty screen when I tried changing the API. It's your call to use the FAFSA endpoint for now and just change it later when the demographics endpoint gets fixed. Whichever you do, just make sure both are consistent since it's pointing at 2 different spots right now depending on whether its development or production

**Comment by wbvtler** [comment]
@tomdng check now

**Comment by tomdng** [comment]
@wbvtler Looks good! I'll start merging now,

**Pull request merged**
