### PR TITLE
Issue 111 algoliav2

### PR DESCRIPTION
**Pull request by arronz99**

### CODE REVIEW

**Comment by wbvtler** [comment]
@arronz99 When I try to use the search-select fields, clicking on options doesn't always work. I might have to try 5 or 6 times before it actually selects the item.


search-select

**Comment by tomdng** [comment]
> 
> 
> @arronz99 When I try to use the search-select fields, clicking on options doesn't always work. I might have to try 5 or 6 times before it actually selects the item.
> 

@wbvtler This is likely my issue with how i implemented the search select component, so I will go ahead and make sure that gets fixed.

**Comment by tomdng** [comment]
@wbvtler I'm trying it on my machine and on mobile and while I noticed it not working once or twice, I had trouble consistently re-creating the issue. What browser did you use and are you using mouse or touchscreen input?

**Comment by wbvtler** [comment]
@tomdng Sure, let's merge this. Can you manage the merge conflicts?

**Comment by tomdng** [comment]
> @tomdng Sure, let's merge this. Can you manage the merge conflicts?

Conflicts should already be fixed. Also here's me showing the new behavior. I'll go ahead and merge this to master and then deploy to production.
find

**Pull request merged**
